import = [
    "~/.config/alacritty/themes/themes/hyper.toml"
]

[shell]
program = "/bin/zellij"
args = [ "options", "--default-shell", "fish" ]

[window.dimensions]
columns = 120
lines = 45

[font]
size = 12

  [font.normal]
  family = "FiraCode Nerd Font Med


